import { Russo_One } from "next/font/google";
import { RootLayoutProps } from "@/types";
import { Metadata } from "next";
import "@/styles/globals.css";

const russoOne = Russo_One({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning className={russoOne.className}>
      <body className={`antialiased`}>
          {children}
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "PTM Kalarisangam",
  description: "Generated by create next app",
};
export default RootLayout;
